=== Kzawery/Biblioteka/database.dtd
<!ELEMENT ksiegarnia (ksiazki, typyOkladek, klienci)>
<!ELEMENT ksiazki (ksiazka+)>


<!ELEMENT ksiazka (tytul, cena, autor, opis, ilosc)>

<!ELEMENT tytul      (#PCDATA)>
<!ELEMENT cena      (#PCDATA)>
<!ELEMENT autor      (#PCDATA)>
<!ELEMENT opis      (#PCDATA)>
<!ELEMENT ilosc      (#PCDATA)>

<!ELEMENT typyOkladek (typOkladki+)>

<!ELEMENT typOkladki (skrot, nazwaTypu)>
<!ELEMENT skrot     (#PCDATA)>
<!ELEMENT nazwaTypu     (#PCDATA)>


<!ELEMENT koszyk (produkt+)>

<!ELEMENT produkt (#PCDATA)>
<!ATTLIST produkt id IDREF #REQUIRED>
<!ELEMENT klienci (klient+)>

<!ELEMENT klient (imie, nazwisko, email, koszyk)>

<!ELEMENT imie      (#PCDATA)>
<!ELEMENT nazwisko       (#PCDATA)>
<!ELEMENT email     (#PCDATA)>

<!ATTLIST klient idKlienta ID #REQUIRED>

<!ATTLIST ksiazka id ID #REQUIRED>

<!ATTLIST ksiazka typo IDREF #REQUIRED>

<!ATTLIST cena jednostkaCeny CDATA #REQUIRED>
<!ATTLIST typyOkladek typOkladki (twarda|miekka) "miekka">
<!ATTLIST typOkladki typo ID #REQUIRED>

=== Kzawery/Biblioteka/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="database.css"?>
<!DOCTYPE ksiegarnia SYSTEM "database.dtd">
<ksiegarnia>
    <ksiazki>
        <ksiazka id="k1" typo="mk">
            <tytul>Przygody Tomka Sawyera</tytul>
            <cena jednostkaCeny="zł">50.99</cena>
            <autor>Mark Twain</autor>
            <opis>Akcja utworu toczy się w końcu XIX w. w miasteczku St. Petersburg w Ameryce nad rzeką Missisipi. Tematem powieści są przygody tytułowego bohatera – Tomka Sawyera i jego rówieśników </opis>
            <ilosc>12</ilosc>
        </ksiazka>

        <ksiazka id="k2" typo="tw">
            <tytul>Przygody Tomka Sawyera</tytul>
            <cena jednostkaCeny="zł">48.99</cena>
            <autor>Mark Twain</autor>
            <opis>Akcja utworu toczy się w końcu XIX w. w miasteczku St. Petersburg w Ameryce nad rzeką Missisipi. Tematem powieści są przygody tytułowego bohatera – Tomka Sawyera i jego rówieśników </opis>
            <ilosc>22</ilosc>
        </ksiazka>

        <ksiazka id="k3" typo="tw">
            <tytul>Wyrwa</tytul>
            <cena jednostkaCeny="zł">40.99</cena>
            <autor>Wojciech Chmielarz</autor>
            <opis>Kiedy Maciej Tomski dowiaduje się, że jego żona Janina zginęła w wypadku samochodowym, myśli, że wali mu się cały świat. Jak powiedzieć dwóm córeczkom, że właśnie straciły matkę? Jak powiedzieć teściom? Jak ma teraz funkcjonować, gdy dotychczasowe, spokojne życie nagle szarzeje i zmienia się w ciąg udręk?</opis>
            <ilosc>32</ilosc>
        </ksiazka>


        <ksiazka id="k4" typo="mk">
            <tytul>Przekręt</tytul>
            <cena jednostkaCeny="zł">30.99</cena>
            <autor>Paulina Świst</autor>
            <opis>Przekręt" to już kolejna odsłona gorącej kryminalnej historii od tajemniczej Pauliny Świst. Zanurz się w świat, którym rządzą chciwość i pożądanie, a bohaterowie przekraczają kolejne granice. Jak daleko posuną się tym razem?</opis>
            <ilosc>24</ilosc>
        </ksiazka>
    
        <ksiazka id="k5" typo="mk">
            <tytul>Papierowy Mag. Mag. Tom 1</tytul>
            <cena jednostkaCeny="zł">20.99</cena>
            <autor>Charlie N. Holmberg</autor>
            <opis>Wciągające fantasy w steampunkowym wydaniu! Wkrocz do świata magów, w którym wszystko jest możliwe. Miej się jednak na baczności.</opis>
            <ilosc>14</ilosc>
        </ksiazka>

        <ksiazka id="k6" typo="tw">
            <tytul>Dom między chmurami. Tom 1</tytul>
            <cena jednostkaCeny="zł">33.99</cena>
            <autor>C. Klobuch</autor>
            <opis>Miłość, poświęcenie i zdrada w pasjonującej opowieści fantasy, w której słowiańska mitologia miesza się z barbarzyńskimi kultami i wszechobecną magią.</opis>
            <ilosc>11</ilosc>
        </ksiazka>

        <ksiazka id="k7" typo="tw">
            <tytul>Kroniki braci. Tom 1. Upadek Lucyfera</tytul>
            <cena jednostkaCeny="zł">32.99</cena>
            <autor>Alec Wendy</autor>
            <opis>"Upadek Lucyfera" to powieść fantastyczna, która ukazuje nam wizję Pierwszych Niebios i początek walki dobra ze złem, a także konsekwencje, które za tym idą.</opis>
            <ilosc>51</ilosc>
        </ksiazka>

        <ksiazka id="k8" typo="mk">
            <tytul>Kroniki braci. Tom 2. Pierwszy Sąd</tytul>
            <cena jednostkaCeny="zł">35.99</cena>
            <autor>Alec Wendy</autor>
            <opis>Trzech archaniołów… Trzech braci… Jeden zdrajca.</opis>
            <ilosc>21</ilosc>
        </ksiazka>

        <ksiazka id="k9" typo="mk">
            <tytul>Becoming. Moja historia</tytul>
            <cena jednostkaCeny="$">12.99</cena>
            <autor>Michelle Obama</autor>
            <opis>“Becoming. Moja historia” to autobiograficzna książka najsłynniejszej Pierwszej Damy USA.</opis>
            <ilosc>21</ilosc>
        </ksiazka>

    </ksiazki>
    
    <typyOkladek>
        <typOkladki typo="tw">
            <skrot>tw</skrot>
            <nazwaTypu>twarda</nazwaTypu>
        </typOkladki>
        <typOkladki typo="mk">
            <skrot>mk</skrot>
            <nazwaTypu>miekka</nazwaTypu>
        </typOkladki>
    </typyOkladek>

    <klienci>
        <klient idKlienta="klient1">
            <imie>Kamil</imie>
            <nazwisko>Nowak</nazwisko>
            <email>kamil.nowak@temp.pl</email>
        </klient>
        

        <klient idKlienta="klient2">
            <imie>Wojtek</imie>
            <nazwisko>Nowak</nazwisko>
            <email>wojtek.nowak@temp.pl</email>
        </klient>

        <klient idKlienta="klient3">
            <imie>Magda</imie>
            <nazwisko>Kowalska</nazwisko>
            <email>magda.kowalskak@temp.pl</email>
        </klient>

        <klient idKlienta="klient4">
            <imie>Kamil</imie>
            <nazwisko>Kowalski</nazwisko>
            <email>k.kowalski@temp.pl</email>
        </klient>

        <klient idKlienta="klient5">
            <imie>Adam</imie>
            <nazwisko>Adamowicz</nazwisko>
            <email>a.adamowicz@temp.pl</email>
        </klient>

        <klient idKlienta="klient6">
            <imie>Wioletta</imie>
            <nazwisko>Grochowska</nazwisko>
            <email>wgrochowska@temp.pl</email>
        </klient>

        <klient idKlienta="klient7">
            <imie>Kamila</imie>
            <nazwisko>Jankowsa</nazwisko>
            <email>KamilaJankowska@temp.pl</email>
        </klient>

        <klient idKlienta="klient8">
            <imie>Kuba</imie>
            <nazwisko>Posochowicz</nazwisko>
            <email>kubaPosochowicz@temp.pl</email>
        </klient>

        <klient idKlienta="klient9">
            <imie>Wiesława</imie>
            <nazwisko>Grzybowa</nazwisko>
            <email>w.grzybowa@temp.pl</email>
        </klient>
    </klienci>

    <koszyki>

        <koszyk idKlienta = "klient1">
                <produkt id="k1">1</produkt>
                <produkt id="k2">2</produkt>
        </koszyk>

        <koszyk idKlienta = "klient2">
                <produkt id="k1">1</produkt>
                <produkt id="k2">2</produkt>
                
        </koszyk>

        <koszyk idKlienta ="klient3">
                <produkt id="k1">1</produkt>
                <produkt id="k2">2</produkt>
        </koszyk>

        <koszyk idKlienta ="klient4">
                <produkt id="k4">3</produkt>
        </koszyk>

        <koszyk idKlienta ="klient5">
                <produkt id="k7">1</produkt>
                <produkt id="k8">1</produkt>
                <produkt id="k1">2</produkt>
        </koszyk>

        <koszyk idKlienta ="klient6">
                <produkt id="k3">1</produkt>
                <produkt id="k4">1</produkt>
                <produkt id="k5">2</produkt>
                <produkt id="k6">3</produkt>
        </koszyk>

        <koszyk idKlienta ="klient7">
                <produkt id="k1">1</produkt>
                <produkt id="k8">1</produkt>
                <produkt id="k7">2</produkt>
                <produkt id="k2">2</produkt>
        </koszyk>

        <koszyk idKlienta ="klient8">
                <produkt id="k7">1</produkt>
                <produkt id="k8">1</produkt>
                <produkt id="k1">2</produkt>
        </koszyk>

        <koszyk idKlienta ="klient9">
                <produkt id="k7">1</produkt>
                <produkt id="k8">1</produkt>
                <produkt id="k9">2</produkt>
        </koszyk>
    </koszyki>

</ksiegarnia>
